# what are programming language -ok so it is hard to  understand binary language so We humans
# make programming language like c,c++,python,java that we can uderstand these languages convert our
# code in binary lang that system understands

# origin of python
'''in 1980's there was a man name guido van rossum who was working on abc language but that was very limited so he decided to make 
a simple and powerfull language in winter holidays and then python launched in 1992 1 verstion of python launched the name given 
by a circus show monty pythons flying circus and he wants a unique name '''

# how pyhton works 
"""so there are two types of lang
1 compile time lang
2 interpreted lang
 An interpreted language is executed line by line with the help of an interpreter, meaning the program is translated and run at the same time.
 Because of this, execution is generally slower, and if an error occurs, the program stops immediately at the line where the error is found. 
 Interpreted languages usually do not produce a separate executable file and are easier to debug and modify, making them suitable for rapid development. 
 Examples include Python and JavaScript.
 
 A compiled (compile-time) language, on the other hand, is translated completely into machine code before execution using a compiler.
 The compiler checks the entire program and reports errors after compilation, and once successfully compiled, the program runs faster because it does not need translation at runtime. 
 Compiled languages generate a separate executable file, use memory more efficiently, and are commonly used for performance-critical applications. Examples include C and C++.
 
 
 so python is a interpreted language which is executed by python virtual machine it converts code into bytes codes also 
  to execute  code we download ide integrated devlopment environment (vs studio) 
 what it stands for we download virtual machine so how we write code in it then we have to write code in terminal and i dont want it
 then we download an environment for it there are many pycharm,jupyter,vs code 
  vs code also requires compiler or interpretor thats why we dwnld also in vs code then whats the use of vm if we want to install something by pip or finding version so then
  the first python vm comes in use .py is the extension for python"""

# difference between output and terminal

"""

 In **VS Code**, the **Terminal** and **Output** panels serve different purposes. The **Terminal** is an interactive panel where you can type commands,
 run programs, execute scripts, use Git commands, and interact directly with the operating system or language runtimes (like Python, Node.js, or Java). 
 It accepts user input and shows results just like a real command-line window. The **Output** panel, on the other hand, is not interactive;
 it is used only to display messages generated by VS Code itself or by extensions, such as build logs, compiler messages, debugger output, or language server notifications.
 In simple terms, the terminal is for **running and controlling programs**, while the output panel is for **viewing logs and messages** produced by VS Code and its tools.
"""

# running first progrram
print("hello piyush")


